travis:
  secure:
    BINSTAR_TOKEN: ZY8/Gz6Y9ZapPb3GoXqMSdtj34ox685ojwx/0lDhgb+bJrpMuTE5fj/WzCFu5rMsoBjz9wx8mn9RPKFapkEyikrbNi27bL3xEVh70RqyqxhsS6JNKsW9pHRlwY4jZE24iknpTkLQZajxZrTMSN6kgYZ0h2UX8kgZKu4pv0GsBF3daJMXkKVvNn17Qfo7+m/H5i6Z2BYO1Kfll7g1GP5TN05nf9DhdIVfRcjx7WkvG5WLPQVRCIaCvMwRfFtN96nqh8hfm3S4BVHZak7jtnhZfU9zvYFT0yvREwB815bGhnveM7MyamZkWfeUr6TACkR+0IBX50O4tiEQsUyNbPs9uSKaurGf4olhCLBm3ktzPutEyoHmPVB+BEjHBOr2aT+4XX91lwp3XAaXNWtum4FyVDKrev4HqoImWaWgZjF/wxFOrUFI3z+miGDje2PT5DsGC42oSYsT4/kVx5e40Gtxr2FPB88QiVl+mthvA5gXWey+49SZ8FmDtQ50MfiZyGxMkxR9DKY7hZ9vxZJlMe6N66ZFDvkpwgDd6+heMX1od8Ho8lMvU9Q9+hACMR2U7IMkYV4ttcdcBJE8eFIvAww6j4ddTsxsI78ZbLcYRPlDqIsnKNIlkYLzJ0uXcQ2fIi/FUSo5Eb5M65jdZMns0JVnIiZpLU76ZqLXUAeXKGR7NUE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
